plotPsiggplot<-function(WT=25, shFli1=26, YK=27, misoList=NULL){
  ind<-c(WT, shFli1, YK)
  require(ggplot2)
  require(reshape2)
  require(wesanderson)
  m<-melt(misoList)
  quantvechigh<-tapply(m$value, INDEX = list(factor(m$Var2), factor(m$L1)), FUN = function(x) quantile(x, 0.75), simplify = TRUE)
  quantveclow<-tapply(m$value, INDEX = list(factor(m$Var2), factor(m$L1)), FUN = function(x) quantile(x, 0.25), simplify = TRUE)
  quantvecmid<-tapply(m$value, INDEX = list(factor(m$Var2), factor(m$L1)), FUN = function(x) quantile(x, 0.5), simplify = TRUE)
  
  m<-cbind(m, apply(m, 1, function(x) quantvechigh[x[2],x[4]]), apply(m, 1, function(x) quantveclow[x[2],x[4]]), apply(m, 1, function(x) quantvecmid[x[2],x[4]]))
  colnames(m)<-c("Event", "Phenotype", "PSI", "Type", "High", "Low", "Mean")
  print(head(m))
  a<-ggplot(m, aes(x=Type, y=Mean, ymin=Low, ymax=High, fill=Phenotype, col=Phenotype))
  a<-a+theme_bw()
  #a<-a+geom_bar(stat="")
  #a<-a+geom_boxplot(alpha=0.5)
  #a<-a+geom_density()
  a<-a+scale_color_manual(values = wes_palette("Zissou")[c(5,1,4)])
  a<-a+geom_pointrange(position=position_dodge(width=0.5), cex=2.65, pch=15)
  #a<-a+geom_line()
  #a<-a+geom_violin()
  #a<-a+stat_summary()
 #a<-a+geom_point(mapping = aes(y=Mean, x=Type, fill=Phenotype), position="dodge")
  #a<-a+geom_errorbar(position = "dodge", width=0.2, aes(col=Phenotype))
  plot(a)
}